[package]
name = "halo2circuit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2-base = { git = "https://github.com/axiom-crypto/halo2-lib.git" }
halo2-ecc = { git = "https://github.com/axiom-crypto/halo2-lib.git" }
poseidon-rs = "0.0.10"
