[package]
name = "halo2circuit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-std = "0.4.0"
getset = "0.1.2"
halo2-base = "0.4.0"
halo2-ecc = "0.4.0"
itertools = "0.12.0"
poseidon-rs = "0.0.10"
serde = "1.0.193"
snark-verifier-sdk = "0.1.6"
