workspace = { members = ["src/rec"] }
[package]
name = "halo2circuit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
dev-graph = ["halo2_proofs/dev-graph", "plotters"]

[dependencies]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v2022_10_22"}
halo2_gadgets = { git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v2022_10_22"}
halo2wrong = { git = "https://github.com/privacy-scaling-explorations/halo2wrong.git", default-features = false, tag = "v2022_10_22"  }
ecdsa = { git = "https://github.com/privacy-scaling-explorations/halo2wrong.git", tag = "v2022_10_22"  }
ecc = { git = "https://github.com/privacy-scaling-explorations/halo2wrong.git", tag = "v2022_10_22"  }
integer = { git = "https://github.com/privacy-scaling-explorations/halo2wrong.git", tag = "v2022_10_22"  }
maingate = { git = "https://github.com/privacy-scaling-explorations/halo2wrong.git", tag = "v2022_10_22"  }
plotters = { version = "0.3.0", optional = true }
tabbycat = { version = "0.1", features = ["attributes"], optional = true }
eth-types = { git = "https://github.com/privacy-scaling-explorations/zkevm-circuits", rev= "37b8aca"}
num-bigint = "0.4.3"
hex = "0.4.3"
arrayvec = "0.7.2"
gadgets = { git = "https://github.com/privacy-scaling-explorations/zkevm-circuits", rev= "37b8aca"}
rand = "0.8"
halo2 = "0.0.0"
group = "0.12.0"
rand_core = { version = "0.6", default-features = false }
