[package]
name = "halo2circuit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2-base = "0.4.0"
halo2-ecc = "0.4.0"
paillier-chip = { git = "https://github.com/aerius-labs/paillier-halo2.git" , branch = "feat/pallier-add" }
pse-poseidon = { git = "https://github.com/aerius-labs/pse-poseidon.git", branch = "feat/stateless-hash" }
halo2-wasm = { git = "https://github.com/metavind/halo2-wasm.git", branch = "feat/target-lib", default-features = false }

poseidon-rs = "0.0.10"
num-bigint = "0.4.4"
num-traits = "0.2.17"
rand = "0.8.5"
serde = "1.0.193"
bigint = "4.4.3"
rand_core = "0.6.4"
wasm-bindgen = "0.2.87"
jemalloc-sys = "0.5.3"
[lib]
crate-type = ["cdylib", "rlib"]
